### PR TITLE
Fix/form draft title

### PR DESCRIPTION
**Pull request by seanwarman**

### CODE REVIEW

**Comment by seanwarman** [comment]
This has gone a little bit off topic because most of the work has gone into making the form fields required from the form.page.js 

The code here is a bit dirty but it works to my knowledge.

https://github.com/ConsensusBot/gitter-gimp/issues/39

**Review by lukeheath — CHANGES_REQUESTED** [review]
This works well for me! A couple of requests: 

1) It would be helpful to indicate which fields are required. Looks like all of them except "Other". Can you add an indicator of which fields are required? I'm picturing a simple asterisk next to the input title. For example: Stakeholders *. Then at the top add "* Indicates required field".

2) Extra points if you can add a "missed-field" class (or something like that) when the user tries to submit the form and missed a required field. Then, create a style that puts a 1px solid red border around missed fields. That will help users find the field they missed. If you get blocked I can help with that, as well!

**Comment by seanwarman** [comment]
I can definitely have a crack at it! :)

**Comment by seanwarman** [comment]
luke, I'm going to make the changes you requested on a new branch because I think there might be loads of merge conflicts down the line otherwise.

here's the new branch name: fix/form-field-checking

**Comment by seanwarman** [comment]
https://github.com/ConsensusBot/fpr-app/pull/57

**Review by lukeheath — APPROVED** [review]

**Pull request merged**
