### PR TITLE
moved opening nav bar ul outside of js condition

### PR DESCRIPTION
**Pull request by seanwarman**

### CODE REVIEW

**Comment by seanwarman** [comment]
https://github.com/ConsensusBot/fpr-app/issues/61

**Comment by lukeheath** [comment]
@seanwarman Thanks for this. Styling looks good, but I noticed that when the "Account" drop down is active, part of the drop down menu is off page which causes a horizontal scroll in the window (see screenshot). We may need to reposition it slightly so that it isn't off screen. I would recommend looking at how Bootstrap handles it in their demos. Maybe they have a class you can put on the last item or something?

image

**Review by lukeheath — CHANGES_REQUESTED** [review]
See comment regarding last drop-down item scrolling off page.

**Comment by lukeheath** [comment]
@seanwarman Same issue is occuring on the last admin drop down menu: 

image

**Comment by seanwarman** [comment]
Sorry I missed your comment there. I've sorted this now. Should work as you asked.

**Review by lukeheath — APPROVED** [review]

**Comment by lukeheath** [comment]
Looks great. Thanks!

**Pull request merged**
